(() => {
  "use strict";
  const O=window.LINKS_OS_CORE, X=window.LINKS_CONFIG;
  if(!O)return;
  const {$,$$,APPS,wm,icon,cat,appArt,escapeHTML,showDialog,announce}=O;
  const opened=Date.now();
  const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(`links98:${k}`))??f}catch(_){return f}};
  const write=(k,v)=>{try{localStorage.setItem(`links98:${k}`,JSON.stringify(v))}catch(_){}};
  const safeOpen=(url,label)=>url?window.open(url,"_blank","noopener,noreferrer"):showDialog({title:"LINKS 98",message:`${label} is not configured yet.`,image:cat("reactions/concerned")});
  const copyCA=async()=>{try{await navigator.clipboard.writeText(X.CONTRACT_ADDRESS)}catch(_){const t=document.createElement("textarea");t.value=X.CONTRACT_ADDRESS;document.body.append(t);t.select();document.execCommand("copy");t.remove()}return transferDialog()};
  const achievements=()=>new Set(read("achievements",["CAT OWNER"]));
  function unlock(name){const a=achievements();if(a.has(name))return;a.add(name);write("achievements",[...a]);showDialog({title:"Achievement Unlocked",message:name,image:cat("celebrate")})}
  function transferDialog(){const b=document.createElement("div");b.className="dialog-backdrop";b.innerHTML=`<section class="dialog"><div class="titlebar"><span class="titlebar-title">Copying...</span></div><div class="dialog-body"><img class="dialog-icon" src="${appArt("installer-cat")}" alt=""><div><strong>COPYING:</strong><br>C:\\LINKS\\contract_address.txt<br><br><strong>TO:</strong><br>Clipboard<progress max="100" value="0"></progress><p data-copy-status>Preparing...</p></div></div></section>`;$("#dialog-layer").append(b);let n=0;const timer=setInterval(()=>{n+=20;$("progress",b).value=n;$("[data-copy-status]",b).textContent=`${"█".repeat(n/10)}${"░".repeat(10-n/10)} ${n}%`;if(n===100){clearInterval(timer);setTimeout(()=>{b.remove();showDialog({title:"Copy Complete",message:"Contract Address copied successfully.",image:appArt("installer-cat")})},350)}},90)}
  const actionButtons=()=>`<div class="crypto-actions"><button class="win-button" data-real="copy">COPY CA</button><button class="win-button" data-real="buy">BUY LINKS</button><button class="win-button" data-real="chart">VIEW CHART</button><button class="win-button" data-real="x">X / COMMUNITY</button></div>`;
  function realActions(win){win.addEventListener("click",e=>{const a=e.target.closest("[data-real]")?.dataset.real;if(a==="copy")copyCA();if(a==="buy")safeOpen(X.BUY_URL,"Official buy URL");if(a==="chart")safeOpen(X.CHART_URL,"Chart URL");if(a==="x")safeOpen(X.X_URL,"Official X URL");if(a==="explorer")safeOpen(X.EXPLORER_URL,"Blockchain explorer URL")})}
  APPS.wallet={title:"LINKS Wallet 98",icon:icon("links"),width:620,height:430,status:"No wallet is connected — real links are marked",render:()=>`<div class="panel crypto-card"><img src="${appArt("computer-hug-cat")}" alt="Links Cat beside a computer"><div><h2>LINKS WALLET</h2><dl class="property-list"><dt>Network:</dt><dd>Robinhood Chain (4663)</dd><dt>Token:</dt><dd>$LINKS</dd><dt>Status:</dt><dd>ONLINE</dd></dl><label>Contract Address<input class="ca-field" value="${escapeHTML(X.CONTRACT_ADDRESS)}" readonly></label></div></div>${actionButtons()}<button class="win-button" data-wallet>INSERT WALLET</button>`,mount:win=>{realActions(win);win.onclick=e=>{if(e.target.closest("[data-wallet]"))showDialog({title:"Insert Wallet",message:"Please insert your EVM wallet into drive A:\n\nNo wallet detected. Links recommends using the actual BUY button.",image:icon("my-computer"),buttons:["Retry","Cancel"]})}}};
  APPS.blockexplorer={title:"LINKS Explorer",icon:icon("internet"),width:720,height:500,status:"SIMULATED ACTIVITY — no live blockchain data",render:()=>`<div class="browser-toolbar"><button class="win-button" data-real="explorer">VIEW REAL EXPLORER</button></div><div class="address-row"><span>Address</span><input value="links://robinhood/activity" readonly></div><div class="panel fake-chain"><h2>LINKS BLOCK EXPLORER</h2><p><strong>FICTIONAL SYSTEM DISPLAY</strong> — not live chain data.</p><table><thead><tr><th>Block</th><th>Transaction</th><th>Action</th><th>Status</th></tr></thead><tbody data-chain><tr><td>#0001998</td><td>CAT → INTERNET</td><td>1 MEME</td><td>CONFIRMED</td></tr><tr><td>#0001999</td><td>UNKNOWN → LINKS</td><td>BUY</td><td>CONFIRMED</td></tr></tbody></table></div>`,mount:win=>{realActions(win);let block=2000;win._chain=setInterval(()=>{const body=$("[data-chain]",win);if(!body)return;const row=document.createElement("tr");row.innerHTML=`<td>#${String(block++).padStart(7,"0")}</td><td>INTERNET → CAT</td><td>MEME</td><td>CONFIRMED</td>`;body.prepend(row);if(body.children.length>6)body.lastElementChild.remove()},4500)},unmount:win=>clearInterval(win._chain)};
  APPS.price={title:"PRICE.EXE",icon:icon("market"),width:430,height:300,menu:false,render:()=>`<div class="panel system-lines"><h2>PRICE.EXE</h2><div>LIVE DATA: <output>NOT CONNECTED</output></div><p>No price, market cap, volume, or holder count is being simulated.</p><button class="win-button" data-real="chart">VIEW CHART</button></div>`,mount:realActions};
  APPS.portfolio={title:"PORTFOLIO.EXE",icon:icon("market"),width:500,height:390,menu:false,status:"DEMO MODE — no wallet data",render:()=>`<div class="panel system-lines"><h2>DEMO MODE</h2><div>LINKS <output>████████████████ 100%</output></div><div>Other Coins 0%</div><div>Diversification: Questionable</div><div>Risk: Cat</div><div>Strategy: Internet</div><button class="win-button" data-refresh>REFRESH</button><p data-portfolio></p></div>`,mount:win=>$("[data-refresh]",win).onclick=()=>$("[data-portfolio]",win).textContent="Nothing changed. Still a cat."};
  APPS.mining={title:"LINKS MINING",icon:icon("my-computer"),width:540,height:360,menu:false,status:"Parody utility — LINKS is not mineable here",render:()=>`<div class="panel mining"><h2>Mining Internet Memes...</h2><p>Hashrate: 3 cats/sec</p><p>Found: <span data-found>0 useful things</span></p><div class="mining-track"><img src="${cat("walk")}" alt=""><progress max="100" value="0"></progress></div><p data-mining>No financial reward. Obviously.</p></div>`,mount:win=>{let n=0;win._mine=setInterval(()=>{n+=4;$("progress",win).value=n;if(n>=100){clearInterval(win._mine);$("h2",win).textContent="MINING COMPLETE";$("[data-found]",win).textContent="+1 MEME";$("[data-mining]",win).textContent="No financial reward. Obviously."}},140)},unmount:win=>clearInterval(win._mine)};
  APPS.firewall={title:"Paper Hands Firewall",icon:icon("recycle-full"),width:600,height:430,status:"PROTECTED",render:()=>`<div class="panel firewall"><h2>PAPER HANDS FIREWALL</h2><p>Status: <strong>PROTECTED</strong></p><p>Protection against: FUD, Panic Selling, Bad Vibes, Random Influencers, Refreshing Chart Every 2 Seconds</p><button class="win-button" data-scan>SCAN SYSTEM</button><pre data-scanlog>Ready.</pre></div>`,mount:win=>$("[data-scan]",win).onclick=()=>{const log=$("[data-scanlog]",win);log.textContent="Scanning...";setTimeout(()=>log.textContent="C:\\brain\\fud.dll       DETECTED\nC:\\wallet\\panic.exe    DETECTED\nC:\\system32\\links.sys  SAFE\n\n2 THREATS FOUND.",900);setTimeout(()=>{const q=document.createElement("button");q.className="win-button";q.textContent="QUARANTINE";q.onclick=()=>{log.textContent+="\n\nfud.dll and panic.exe moved to Recycle Bin.";q.disabled=true};log.after(q)},1000)}};
  APPS.crypto={title:"LINKS Crypto Properties",icon:icon("links"),width:520,height:420,menu:false,render:()=>`<div class="panel settings-panel"><h2>CRYPTO SETTINGS</h2><dl class="property-list"><dt>Network:</dt><dd>Robinhood Chain</dd><dt>Trading:</dt><dd>Enabled</dd><dt>Memes:</dt><dd>Enabled</dd><dt>Destination:</dt><dd>Higher</dd></dl>${["Enable memes","Show market notifications","Prevent emotional selling","Allow cat access to internet","Automatically believe"].map(x=>`<label><input type="checkbox" checked> ${x}</label>`).join("")}<label><input type="checkbox" data-ticker ${read("ticker",false)?"checked":""}> Show desktop LINKS status ticker</label><label><input type="checkbox" data-bull ${read("bullish",true)?"checked":""}> Bullish Mode</label></div>`,mount:win=>win.onchange=e=>{if(e.target.matches("[data-ticker]")){write("ticker",e.target.checked);ticker(e.target.checked)}if(e.target.matches("[data-bull]")){write("bullish",e.target.checked);document.body.classList.toggle("bullish-mode",e.target.checked)}}};
  APPS.neighborhood={title:"Network Neighborhood",icon:icon("community"),width:650,height:440,status:"5 computer(s)",render:()=>`<div class="file-grid">${["ROBINHOOD CHAIN","INTERNET","MEME SERVER","CAT SERVER","MOON"].map(x=>`<button class="file-item" data-server="${x}"><img src="${icon("my-computer")}" alt=""><span>${x}</span></button>`).join("")}</div>`,mount:win=>{let moon=read("moonAttempts",0);const handleServer=e=>{const x=e.target.closest("[data-server]")?.dataset.server;if(x==="ROBINHOOD CHAIN")showDialog({title:"ROBINHOOD CHAIN (4663)",message:"STATUS: ONLINE\nRPC: rpc.mainnet.chain.robinhood.com",image:icon("internet")});if(x==="INTERNET")wm.open("internet");if(x==="MEME SERVER")wm.open("memes");if(x==="CAT SERVER")wm.open("classified");if(x==="MOON"){moon++;write("moonAttempts",moon);if(moon>=5)unlock("MOON CALLER");showDialog({title:"Network Error",message:"Network path not found.",image:cat("reactions/shocked"),buttons:["Retry","Cancel"]})}};win.ondblclick=handleServer;win.onclick=e=>{if(window.innerWidth<=600)handleServer(e)}}};
  APPS.achievements={title:"LINKS Achievements",icon:icon("document"),width:580,height:430,status:"Stored on this computer",render:()=>`<div class="achievement-list">${["CAT OWNER","INTERNET EXPLORER","DIAMOND PAWS","SYSTEM ADMIN","ARCHAEOLOGIST","MOON CALLER","MEME ENGINEER","TOUCH GRASS","DATA TRANSFER","THE INTERNET CAT"].map(x=>`<div><span>${achievements().has(x)?"☑":"☐"}</span><strong>${x}</strong></div>`).join("")}</div>`};
  APPS.mail={title:"LINKS Mail",icon:icon("community"),width:680,height:460,status:"Working Offline",render:()=>`<div class="mail-shell"><div>${[["system@links98","Welcome to the Internet","Welcome."],["cat@localhost","stop clicking sell.exe","please."],["moon@internet","RE: connection request","still processing."]].map((m,i)=>`<button data-mail="${i}"><strong>${m[1]}</strong><small>From: ${m[0]}</small></button>`).join("")}</div><article data-message><h2>LINKS Mail</h2><p>Select a message.</p></article></div>`,mount:win=>win.onclick=e=>{const i=e.target.closest("[data-mail]")?.dataset.mail;if(i==null)return;const data=[["Welcome to the Internet","Welcome."],["stop clicking sell.exe","please."],["RE: connection request","still processing."]][i];$("[data-message]",win).innerHTML=`<h2>${data[0]}</h2><p>${data[1]}</p>`}};

  // APPS.internet is owned by app.js. Do not replace the full browser runtime here.
  APPS.recycle={title:"Recycle Bin — Crypto Edition",icon:icon("recycle-full"),width:680,height:470,status:"6 deleted emotional decisions",render:()=>`<div class="file-grid">${["SELL.EXE","PAPERHANDS.DLL","FUD.TXT","PANIC.EXE","BAD_ENTRY.BMP","JEET.EXE"].map(n=>`<button class="file-item" data-trash="${n}"><img src="${icon("document")}" alt=""><span>${n}</span></button>`).join("")}</div>`,mount:win=>{const handleTrash=e=>{const n=e.target.closest("[data-trash]")?.dataset.trash;if(!n)return;if(n==="SELL.EXE"){unlock("DIAMOND PAWS");showDialog({title:"Warning",message:"Restoring SELL.EXE may negatively affect system morale.\n\nSELL.EXE cannot be restored.\nReason: LINKS CAT is sitting on it.",image:cat("warning-cat")})}else showDialog({title:n,message:"This deleted file is safer in quarantine.",image:cat("reactions/confident")})};win.ondblclick=handleTrash;win.onclick=e=>{if(window.innerWidth<=600)handleTrash(e)};win.oncontextmenu=e=>{const n=e.target.closest("[data-trash]")?.dataset.trash;if(!n)return;e.preventDefault();showDialog({title:`${n} Properties`,message:"Location: Recycle Bin\nStatus: Deleted for a reason\nOwner: CAT.EXE",image:icon("document")})}}};
  const commands={help:"Commands: help links ca copyca buy chart price status wallet holders moon bullish sell jeet fud rug gm gn meow whoami ping internet history\nHidden commands may exist.",links:"LINKS CAT INTERNET PROTOCOL\nSTATUS: RUNNING",ca:`Contract Address:\n${X.CONTRACT_ADDRESS}`,status:"LINKS.EXE       RUNNING\nMEMES.DLL       RUNNING\nINTERNET        CONNECTED\nROBINHOOD.SYS   ONLINE\nSELL.EXE        NOT FOUND",holders:"NOT CONNECTED\nNo holder count is being fabricated.",moon:"Pinging moon...\n\nReply from moon:\ndistance=HIGHER\nstatus=SOON™",bullish:"Bullish mode already enabled.",sell:"ERROR 404:\nSELL BUTTON NOT FOUND",jeet:"Access denied.",fud:"Deleting FUD...\n████████████ 100%\nComplete.",rug:"RUG.DLL not installed.",gm:"gm.",gn:"Links does not sleep.\nExcept when he does.",meow:"meow.",whoami:"internet_user",ping:"Reply from internet: bytes=cats time=56k TTL=98",internet:"THE INTERNET is connected. Somehow.","sudo links":"LINKS already has administrator privileges.","sudo sell":"Permission denied by: LINKS.EXE"};
  APPS.terminal={title:"LINKS Terminal",icon:icon("terminal"),width:670,height:450,menu:false,render:()=>`<div class="terminal"><pre class="terminal-output">LINKS CAT TERMINAL\nCrypto System Expansion loaded.\n\n</pre><label class="terminal-line"><span>C:\\&gt;&nbsp;</span><input class="terminal-input" autocomplete="off" spellcheck="false"></label></div>`,mount:win=>{const i=$("input",win),o=$("pre",win),history=[];i.onkeydown=e=>{if(e.key!=="Enter")return;const raw=i.value.trim(),cmd=raw.toLowerCase();history.push(raw);o.textContent+=`C:\\> ${raw}\n`;i.value="";if(cmd==="clear")o.textContent="";else if(cmd==="copyca"){copyCA();o.textContent+="Contract Address copied to clipboard.\n\n"}else if(cmd==="buy"){o.textContent+="Opening LINKS acquisition protocol...\n\n";safeOpen(X.BUY_URL,"Official buy URL")}else if(cmd==="chart"){o.textContent+="Opening configured chart...\n\n";safeOpen(X.CHART_URL,"Chart URL")}else if(cmd==="wallet")wm.open("wallet");else if(cmd==="price")wm.open("price");else if(cmd==="internet")wm.open("internet");else if(cmd==="history")o.textContent+=history.join("\n")+"\n\n";else if(cmd==="sudo links"){unlock("SYSTEM ADMIN");o.textContent+=commands[cmd]+"\n\n"}else if(cmd==="sudo remove links")o.textContent+="CRITICAL SYSTEM WARNING\nRemoving LINKS.EXE will remove:\nInternet\nMemes\nDesktop\nMouse\nHope\n\nACCESS DENIED. Nice try.\n\n";else o.textContent+=(commands[cmd]||`'${raw}' is not recognized.`)+"\n\n";$(".terminal",win).scrollTop=99999};i.focus()}};

  const poses=["sit","stand","point","computer","celebrate","walk"], backgrounds=["Desktop","Windows Error","CRT","Internet","Chart","Recycle Bin","Moon","Terminal"], captions=["SELL BUTTON NOT FOUND","CAT.EXE IS RUNNING","INTERNET MONEY","HOLD MODE ENABLED","STILL HERE","LINKS WAS HERE","CHECKING THE CHART","NO THOUGHTS JUST LINKS"];
  APPS.mememaker={title:"LINKS MEME MAKER 98",icon:icon("memes"),width:780,height:590,status:"Community image tool — generated locally",render:()=>`<div class="meme-maker"><div class="meme-controls"><label>Pose<select data-pose>${poses.map(x=>`<option>${x}</option>`).join("")}</select></label><label>Background<select data-bg>${backgrounds.map(x=>`<option>${x}</option>`).join("")}</select></label><label>Top text<input data-top value="CAT.EXE IS RUNNING"></label><label>Bottom text<input data-bottom value="SELL BUTTON NOT FOUND"></label><button class="win-button" data-meme="new">NEW</button><button class="win-button" data-meme="random">I'M FEELING LINKY</button><button class="win-button" data-meme="save">SAVE</button><button class="win-button" data-meme="copy">COPY</button></div><canvas width="640" height="480" data-canvas></canvas></div>`,mount:win=>{const c=$("canvas",win),ctx=c.getContext("2d"),draw=()=>{const bg=$("[data-bg]",win).value,pose=$("[data-pose]",win).value;ctx.fillStyle=bg==="Terminal"||bg==="CRT"?"#001500":bg==="Windows Error"?"#c0c0c0":bg==="Moon"?"#07132e":"#008080";ctx.fillRect(0,0,640,480);ctx.strokeStyle="#fff";ctx.lineWidth=4;ctx.strokeRect(12,12,616,456);ctx.fillStyle="#fff";ctx.textAlign="center";ctx.font="bold 36px Impact, sans-serif";ctx.strokeStyle="#000";ctx.lineWidth=6;const text=(s,y)=>{ctx.strokeText(s.toUpperCase(),320,y,590);ctx.fillText(s.toUpperCase(),320,y,590)};const img=new Image();img.onload=()=>{ctx.drawImage(img,190,85,260,310);text($("[data-top]",win).value,52);text($("[data-bottom]",win).value,455)};img.src=cat(pose)};win.oninput=draw;win.onclick=async e=>{const a=e.target.closest("[data-meme]")?.dataset.meme;if(a==="new"){$("[data-top]",win).value="";$("[data-bottom]",win).value="";draw()}if(a==="random"){$("[data-pose]",win).value=poses[Math.random()*poses.length|0];$("[data-bg]",win).value=backgrounds[Math.random()*backgrounds.length|0];$("[data-top]",win).value=captions[Math.random()*captions.length|0];$("[data-bottom]",win).value=captions[Math.random()*captions.length|0];draw()}if(a==="save"){const link=document.createElement("a");link.download="links-meme.png";link.href=c.toDataURL();link.click();unlock("MEME ENGINEER")}if(a==="copy"){try{const blob=await new Promise(r=>c.toBlob(r));await navigator.clipboard.write([new ClipboardItem({"image/png":blob})]);announce("Meme copied to clipboard.");unlock("MEME ENGINEER")}catch(_){showDialog({title:"Meme Maker",message:"Image clipboard is unavailable. Use SAVE instead.",type:"error"})}}};draw()}};

  function ticker(on=read("ticker",false)){let t=$("#links-ticker");if(on&&!t){t=document.createElement("button");t.id="links-ticker";t.className="links-ticker";t.innerHTML="<strong>LINKS STATUS</strong><span>LINKS — ONLINE</span><span>ROBINHOOD — CONNECTED</span><span>INTERNET — WORKING</span>";$("#desktop").append(t);t.onclick=()=>wm.open("market")}if(!on)t?.remove()}
  // Submenus are managed hierarchically in features.js and app.js
  const control=APPS.control, oldRender=control.render, oldMount=control.mount;control.render=()=>oldRender().replace("</div>",`<button class="file-item" data-control="Crypto Settings"><img src="${icon("links")}" alt=""><span>Crypto Settings</span></button></div>`);control.mount=win=>{oldMount(win);win.addEventListener("dblclick",e=>{if(e.target.closest("[data-control]")?.dataset.control==="Crypto Settings")wm.open("crypto")})};
  const tray=$(".tray");tray.insertAdjacentHTML("afterbegin",`<button class="tray-button crypto-tray" title="Robinhood Chain (4663)">RHO</button><button class="tray-button crypto-tray" title="Internet Connected">NET</button><button class="tray-button crypto-tray cat-process" title="LINKS.EXE Running">CAT</button>`);$(".cat-process").onclick=()=>showDialog({title:"LINKS STATUS",message:`Process: LINKS.EXE\nState: Running\nUptime: ${Math.floor((Date.now()-opened)/1000)} seconds\nMemes generated: ${achievements().has("MEME ENGINEER")?1:0}`,image:cat("sit")});
  document.body.classList.toggle("bullish-mode",read("bullish",true));ticker();
  const oldOpen=wm.open.bind(wm);wm.open=(key,opt)=>{const result=oldOpen(key,opt);if(key==="internet")unlock("INTERNET EXPLORER");return result};
})();
